pipeline {
    agent any
    stages {
         
stage ('Build') {

steps {

sh 'mvn clean package'

}

}

stage ('Publish') {
steps {
// Add steps to publish artifacts or deploy the appli
// For example, you can use the 'archiveArtifacts' st
archiveArtifacts 'target/ *. jar'
}
    }
}
}
